### ISSUE TITLE
Query: Does this make use of "lighthouse" library

### ISSUE THREAD

**Issue by vikramvi** [Everettss/test-website-performance-with-puppeteer#1]
It is not clear to me if you've used "lighthouse" along with "puppeteer" or just "puppeteer"

My requirement is to use "lighthouse" in program to check performance of web page through jenkins builds.

Currently I've this setup with godaddy's timings library and want to compare against "lighthouse"

Thanks in advance.

**Comment by Everettss** [comment]
I'm using [only **puppeteer**](https://github.com/Everettss/test-website-performance-with-puppeteer/blob/master/package.json#L11) in this repo. If you are looking for some only basic page performance **lighthouse** [looks suitable](https://github.com/paulirish/pwmetrics/). But if you want a more robust solution with some custom adjustments I'm proposing **puppeteer**.

**Comment by vikramvi** [comment]
Thanks a ton for detailed answer and pointer as well.
